version: "3.8"
services:
    app:
        container_name: example-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
            - phpmyadmin
        networks:
            - lion
    db:
        image: mysql
        container_name: example-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'example'
            MYSQL_PASSWORD: 'lion'
            MYSQL_ROOT_PASSWORD: 'lion'
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - lion
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: example-phpmyadmin
        restart: unless-stopped
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'lion'
            MYSQL_ROOT_PASSWORD: 'lion'
        networks:
            - lion
volumes:
    mysql_data:
networks:
    lion:
        driver: bridge
